# silly-mathgen-tree .travis.yml

language: java

jdk:
    - openjdk11

addons:
    apt:
        update: true

notifications:
    email:
        recipients:
            - asterios.raptis@web.de
        on_failure: always

after_success:
    - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
    - bash <(curl -s https://codecov.io/bash)
